CREATE TABLE users (
  id VARCHAR(40) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) UNIQUE,
  plan VARCHAR(40) NOT NULL DEFAULT 'Free',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE artists (
  id VARCHAR(40) PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  country VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE albums (
  id VARCHAR(40) PRIMARY KEY,
  artist_id VARCHAR(40) NOT NULL REFERENCES artists(id),
  title VARCHAR(180) NOT NULL,
  release_year INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE songs (
  id VARCHAR(40) PRIMARY KEY,
  artist_id VARCHAR(40) NOT NULL REFERENCES artists(id),
  album_id VARCHAR(40) REFERENCES albums(id),
  title VARCHAR(180) NOT NULL,
  genre VARCHAR(80) NOT NULL,
  mood VARCHAR(80),
  duration_seconds INTEGER NOT NULL,
  audio_object_key VARCHAR(240) NOT NULL,
  play_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE playlists (
  id VARCHAR(40) PRIMARY KEY,
  user_id VARCHAR(40) NOT NULL REFERENCES users(id),
  name VARCHAR(160) NOT NULL,
  description TEXT,
  theme VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE playlist_songs (
  playlist_id VARCHAR(40) NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
  song_id VARCHAR(40) NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (playlist_id, song_id)
);

CREATE TABLE user_favorites (
  user_id VARCHAR(40) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  song_id VARCHAR(40) NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, song_id)
);
